### ISSUE TITLE
Too few arguments to function Dmind\Cookieman\DataProcessing\TypoScriptSettingsProcessor::__construct(), 0 passed in 

### ISSUE THREAD

**Issue by hartundweich** [dmind-gmbh/extension-cookieman#288]
Today I updated a Typo3 V9 installation to Typo3 V10 - it is running on PHP 7.2
After upgrading the extension cookieman to 2.11.1 it throws me an error saying:

`Too few arguments to function Dmind\Cookieman\DataProcessing\TypoScriptSettingsProcessor::__construct(), 0 passed in ....`

When I modify the TypoScriptSettingsProcessor.php file to the old version everything is working like a charm. Also no luck with version 2.9.1 of cookieman. Am I missing something or ist it a PHP 7.2 thing?

**Comment by jonaseberle** [comment]
This relies on Dependency Injection, using a [Services.yaml](https://github.com/dmind-gmbh/extension-cookieman/blob/master/Configuration/Services.yaml). 
Make sure to use the InstallTool (!) clear cache function 
![image](https://user-images.githubusercontent.com/1678001/203363621-fc44ba48-53e5-42ea-9772-ae403d59e461.png)
after changing files related to DI.

I have not used PHP 7.2 for ages and our automated tests do not test it either... but I don't see why it should not work.

**Comment by hartundweich** [comment]
Thank you - flushed the cache a few times before but not with the InstallTool function. Thank you for your support... it was the first time I had to do this this way - since now the "normal flush" via the head tools was enough to keep things working.
![grafik](https://user-images.githubusercontent.com/18597291/203495677-56fb2b3f-8f7c-4071-83d0-652658ed661b.png)
